name: Deploy to Salesforce

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Salesforce Authentication
        env:
          SALESFORCE_DEVHUB_USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
          SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          npx sfdx force:auth:jwt:grant \
            --username "${SALESFORCE_DEVHUB_USERNAME}" --setdefaultdevhubusername \
            --clientid "${SALESFORCE_CONSUMER_KEY}" \
            --jwtkeyfile server.key

      - name: Build, Test & Deploy
        id: build_test_deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: RunLocalTests
          WAIT: 120

      - name: Clean Up Files
        run: node ./scripts/node-scripts/clean-up-files/clean-up.js

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
